# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-27 06:57
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(max_length=500, verbose_name='message')),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
